### ISSUE TITLE
Bug in the app

### ISSUE THREAD

**Issue by gray-adeyi** [steelthedev/gin-mvc-cli#2]
The application quits when 'q' is in the name of the project. and also I'm unable to type the letter 'k','j' when creating a project name

**Comment by steelthedev** [comment]
I apologize for this, I will fix that immediately.

**Comment by steelthedev** [comment]
@gray-adeyi I have fixed the issues now. You can clone and try it now.

**Comment by gray-adeyi** [comment]
Nice. will try this out soonest

**Comment by gray-adeyi** [comment]
Tried it out @steelthedev it works fine now
